#!/usr/bin/env bash
# Setup for candy checker
echo '************************'
echo '* Setup Candy checkers *'
echo '************************'
echo "This script is designed for ubuntu Ubuntu 16 "
options=("Install Requirements"
        "Give the credentials"
        "Exit")
select opt in "${options[@]}"
do
case $opt in
"Install Requirements")
echo 'updating system'
apt update
echo 'Installing python and pip'
apt install python python3-pip -y
echo 'Installing requests module'
pip3 install requests
;;

"Give the credentials")
read -p "Give me your user, please: " USER
read -p "Give me your password, please: " PASS
echo 'If you dont know which is your APi, you can find on: '
echo 'https://intranet.hbtn.io/dashboards/my_tools'
read -p "Give me your API key: " API
echo 'Your user is: '
echo $USER
echo 'Your Password is: '
echo $PASS
echo 'Your API is: '
echo $API
echo {\'api_key\': $API,} > test.conf
cat test.conf
break
;;

"Exit")                                                                                                                                                              
 break                                                                                                                                                            
 ;;                                                                                                                                                               
 *) echo invalid option;;
esac
done 

